expenseManager:
  image: cjmason8/expense-manager:latest
  environment:
    DB_URL: jdbc:postgresql://172.17.0.1:5432/expensemanager
    DB_USER: postgres
    DB_PASS: jade76
    DB_DRIVER: org.postgresql.Driver
    HIBERNATE_DIALECT: au.com.mason.expensemanager.dao.CustomPostgreSQLDialect
    #HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    HIBERNATE_HBM2DDL_AUTO: update
    AUTH_SERVICE_END_POINT: http://172.17.0.1:8082
  ports:
    - "8083:8080"
  volumes:
    - /applogs:/applogs
    
